name: stats-exercises
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - voila
  - jupyter
  - ipywidgets